# Generated by Django 4.2.11 on 2024-09-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_job_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
    ]
