# Generated by Django 4.2.11 on 2024-09-29 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_room', to='jobs.job'),
        ),
    ]
