# Generated by Django 4.2.11 on 2024-10-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0035_message_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'Applicant'), (1, 'Employer')], default=0, null=True),
        ),
    ]
