# Generated by Django 4.2.11 on 2024-10-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits, spaces, and punctuation allowed.', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
