# Generated by Django 4.2.11 on 2024-10-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0038_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='applied_job',
        ),
        migrations.AddField(
            model_name='invoice',
            name='product_item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
