# Generated by Django 4.2.11 on 2024-10-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0040_jobseeker_applied_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='applied_job',
        ),
    ]
