# Generated by Django 4.2.11 on 2024-10-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0041_remove_jobseeker_applied_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-id']},
        ),
    ]
