# Generated by Django 4.2.11 on 2024-10-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0042_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-payment_date']},
        ),
        migrations.AddField(
            model_name='invoice',
            name='daily_post_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invoice',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
