# Generated by Django 4.2.11 on 2024-10-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0043_alter_invoice_options_invoice_daily_post_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='daily_post_limit',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
