# Generated by Django 4.2.11 on 2024-10-08 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0044_alter_invoice_daily_post_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
