# Generated by Django 4.2.11 on 2024-10-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0045_remove_jobseeker_areas_remove_jobseeker_experience_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-id']},
        ),
    ]
